### ISSUE TITLE
Travis failure.

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1009]
@sbrunner @pgiraud Since yesterday Travis is failling. 
Has something been changed and do we need to modify something ? 

```
Traceback (most recent call last):
  File ".build/venv/bin/c2c-template", line 9, in <module>
    load_entry_point('c2c.template==1.2.0.dev2', 'console_scripts', 'c2c-template')()
  File "/home/travis/build/Geoportail-Luxembourg/geoportailv3/.build/venv/local/lib/python2.7/site-packages/c2c/template.py", line 185, in main
    _proceed(files, used_vars, options)
  File "/home/travis/build/Geoportail-Luxembourg/geoportailv3/.build/venv/local/lib/python2.7/site-packages/c2c/template.py", line 209, in _proceed
    bottle_template(files, used_vars, engine)
  File "/home/travis/build/Geoportail-Luxembourg/geoportailv3/.build/venv/local/lib/python2.7/site-packages/c2c/template.py", line 240, in bottle_template
    template, **used_vars
  File "/home/travis/build/Geoportail-Luxembourg/geoportailv3/.build/venv/bin/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/home/travis/build/Geoportail-Luxembourg/geoportailv3/.build/venv/bin/bottle.py", line 3280, in render
    return self.tpl.render(**_defaults)
  File "/home/travis/build/Geoportail-Luxembourg/geoportailv3/.build/venv/local/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/travis/build/Geoportail-Luxembourg/geoportailv3/.build/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/travis/build/Geoportail-Luxembourg/geoportailv3/.build/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/travis/build/Geoportail-Luxembourg/geoportailv3/.build/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "node_modules_ngeo__tx_config_mako", line 21, in render_body
AttributeError: 'Undefined' object has no attribute 'strip'
make: *** [node_modules/ngeo/.tx/config] Error 1
```

**Comment by petzlux** [comment]
looks related to transifex integration in ngeo

https://github.com/camptocamp/ngeo/commit/e0d7a9d4f6484ad14f4d3a8a293f4be84b378602#diff-1d5124e0e3f36737c2055a7235f9dd52R4

**Comment by sbrunner** [comment]
In the `geoportailv3.mk` file you should do:
```diff
-TEMPLATE_EXCLUDE += LUX_alembic/script.py.mako
+TEMPLATE_EXCLUDE += LUX_alembic/script.py.mako node_modules
```
and it should fix the issue.
I will also add this the folder in the CONST_Makefile ...
Sorry for the inconvenience :-/

**Comment by rmichaelis** [comment]
It seems to work. Thanks for the support.
