### ISSUE TITLE
Printing a label returns an error

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1035]
```
AssertionError: Failure: white is not a valid color
    at new goog.asserts.AssertionError (http://beta.geoportail.lu/main/wsgi/node_modules/openlayers/node_modules/cl…7315d15a4c296321b220b84269a0d9c2d94c/closure/goog/asserts/asserts.js:62:20)
    at Object.goog.asserts.fail (http://beta.geoportail.lu/main/wsgi/node_modules/openlayers/node_modules/cl…315d15a4c296321b220b84269a0d9c2d94c/closure/goog/asserts/asserts.js:176:32)
    at Object.ol.color.fromStringInternal_ (http://beta.geoportail.lu/main/wsgi/node_modules/openlayers/src/ol/color/color.js:246:18)
    at Object.fromString (http://beta.geoportail.lu/main/wsgi/node_modules/openlayers/src/ol/color/color.js:190:32)
    at Object.ol.color.asArray (http://beta.geoportail.lu/main/wsgi/node_modules/openlayers/src/ol/color/color.js:110:21)
    at ngeo.Print.encodeTextStyle_ (http://beta.geoportail.lu/main/wsgi/node_modules/ngeo/src/services/print.js:663:38)
    at ngeo.Print.encodeVectorStyle_ (http://beta.geoportail.lu/main/wsgi/node_modules/ngeo/src/services/print.js:509:10)
    at ngeo.Print.encodeVectorLayer_ (http://beta.geoportail.lu/main/wsgi/node_modules/ngeo/src/services/print.js:438:14)
    at ngeo.Print.encodeLayer (http://beta.geoportail.lu/main/wsgi/node_modules/ngeo/src/services/print.js:223:10)
    at null.<anonymous> (http://beta.geoportail.lu/main/wsgi/proj/45d726e622aa4066aa0e00bead880dc0/js/print/printdirective.js:495:21)

```

**Comment by rmichaelis** [comment]
fixed by #1050
