### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1130]
Hi, 
I am trying to install a docker image from scratch for the geoportailv3 webserver, but I run into the following problem

````
[root@ee6d09e74dc3 app]# make -f main.mk build
./node_modules/openlayers/node_modules/.bin/closure-util build build.json .build/build.js
info closure-util Reading build config
info closure-util Getting Closure dependencies
info closure-util Compiling 433 sources
ERR! compile java.lang.NullPointerException: No warning class for name: checkStructDictInheritance
ERR! compile
ERR! compile
ERR! compile  at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:250)
ERR! compile
ERR! compile
ERR! compile  at com.google.javascript.jscomp.DiagnosticGroups.setWarningLevel(DiagnosticGroups.java:526)
ERR! compile
ERR! compile
ERR! compile  at com.google.javascript.jscomp.AbstractCommandLineRunner.setRunOptions(AbstractCommandLineRunner.java:329)
ERR! compile  at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1048)
ERR! compile  at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:549)
ERR! compile  at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:1407)
ERR! compile
ERR! closure-util Process exited with non-zero status, see log for more detail: 254
make: *** [.build/build.js] Error 1````

when I run npm install openlayers by hand in the container, I don't have any errors..

@sbrunner any idea what this could be about?

**Comment by jaykayone** [comment]
Problem solved, I was not on HEAD

**Comment by elemoine** [comment]
Glad you fixed it :)

**Comment by jaykayone** [comment]
docker here we come
