### ISSUE TITLE
Error Travis

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1200]
Hi @sbrunner 

Since yesterday afternoon I get this error message during the checks.
I don't find in our project where the version of gslint is fixed. Do you have an idea ? 
Is-it in ngeo or in c2cgeoportal ?

```
 .build/venv/bin/gjslint --help
Traceback (most recent call last):
  File ".build/venv/bin/gjslint", line 9, in <module>
    load_entry_point('closure-linter==2.3.13', 'console_scripts', 'gjslint')()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/closure_linter/gjslint.py", line 44, in <module>
    import gflags as flags
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/gflags/__init__.py", line 57, in <module>
    from gflags import _helpers
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/gflags/_helpers.py", line 51, in <module>
    import gflags.third_party.pep257 as pep257
ImportError: No module named third_party.pep257
```

**Comment by sbrunner** [comment]
Neither, that's door to be related to setuptool, see #544

**Comment by rmichaelis** [comment]
Ok Thanks.

**Comment by fredj** [comment]
FYI, we don't use closure-linter anymore (the project is deprecated) and we switched to eslint

**Comment by rmichaelis** [comment]
Thanks for the information.
I'm now migrating to eslint, and it seems that we were leazy with parameter documentation. :-)
