### ISSUE TITLE
Recenter on feature is broken

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1503]
http://apps.geoportail.lu/exemple_api/apiv3_demo.html

"NetworkError: 500 Internal Server Error - http://apiv3.geoportail.lu/api/wsgi/getfeatureinfo?fid=359_061F00614004236&tooltip"
getfeat...tooltip
SyntaxError: JSON.parse: unexpected character at line 2 column 5 of the JSON data

**Comment by jaykayone** [comment]
```
Tue Oct 11 14:37:56.214853 2016] [:error] [pid 53387] [remote 10.111.80.101:40] URL: http://apiv3.geoportail.lu/api/wsgi/getfeatureinfo?fid=359_061F00614004236&tooltip
[Tue Oct 11 14:37:56.214875 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/weberror/errormiddleware.py', line 162 in __call__
[Tue Oct 11 14:37:56.214879 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   app_iter = self.application(environ, sr_checker)
[Tue Oct 11 14:37:56.214881 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/fanstatic/publisher.py', line 219 in __call__
[Tue Oct 11 14:37:56.214883 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   return self.app(environ, start_response)
[Tue Oct 11 14:37:56.214886 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
[Tue Oct 11 14:37:56.214888 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   response = request.get_response(self.app)
[Tue Oct 11 14:37:56.214890 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/webob/request.py', line 1320 in send
[Tue Oct 11 14:37:56.214907 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   application, catch_exc_info=False)
[Tue Oct 11 14:37:56.214909 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/webob/request.py', line 1284 in call_application
[Tue Oct 11 14:37:56.214911 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   app_iter = application(self.environ, start_response)
[Tue Oct 11 14:37:56.214913 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 243 in __call__
[Tue Oct 11 14:37:56.214915 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   response = self.invoke_subrequest(request, use_tweens=True)
[Tue Oct 11 14:37:56.214917 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 218 in invoke_subrequest
[Tue Oct 11 14:37:56.214919 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   response = handle_request(request)
[Tue Oct 11 14:37:56.214921 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid/tweens.py', line 21 in excview_tween
[Tue Oct 11 14:37:56.214923 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   response = handler(request)
[Tue Oct 11 14:37:56.214925 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 94 in tm_tween
[Tue Oct 11 14:37:56.214927 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   reraise(*exc_info)
[Tue Oct 11 14:37:56.214929 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 75 in tm_tween
[Tue Oct 11 14:37:56.214931 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   response = handler(request)
[Tue Oct 11 14:37:56.214932 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 164 in handle_request
[Tue Oct 11 14:37:56.214934 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   response = view_callable(context, request)
[Tue Oct 11 14:37:56.214936 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid/config/views.py', line 353 in rendered_view
[Tue Oct 11 14:37:56.214947 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   result = view(context, request)
[Tue Oct 11 14:37:56.215035 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid/config/views.py', line 481 in _class_requestonly_view
[Tue Oct 11 14:37:56.215040 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   response = getattr(inst, attr)()
[Tue Oct 11 14:37:56.215136 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/geoportailv3/views/getfeatureinfo.py', line 290 in get_feature_info
[Tue Oct 11 14:37:56.215141 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   'geoportailv3:' + path + template, context)
[Tue Oct 11 14:37:56.215143 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid/renderers.py', line 83 in render
[Tue Oct 11 14:37:56.215147 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   result = helper.render(value, None, request=request)
[Tue Oct 11 14:37:56.215159 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid/renderers.py', line 436 in render
[Tue Oct 11 14:37:56.215162 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   result = renderer(value, system_values)
[Tue Oct 11 14:37:56.215164 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py', line 156 in __call__
[Tue Oct 11 14:37:56.215168 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   reraise(MakoRenderingException(errtext), None, exc_info[2])
[Tue Oct 11 14:37:56.215170 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py', line 148 in __call__
[Tue Oct 11 14:37:56.215172 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   result = template.render_unicode(**system)
[Tue Oct 11 14:37:56.215174 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/mako/template.py', line 452 in render_unicode
[Tue Oct 11 14:37:56.215178 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   as_unicode=True)
[Tue Oct 11 14:37:56.215180 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py', line 803 in _render
[Tue Oct 11 14:37:56.215183 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   **_kwargs_for_callable(callable_, data))
[Tue Oct 11 14:37:56.215185 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py', line 835 in _render_context
[Tue Oct 11 14:37:56.215188 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
[Tue Oct 11 14:37:56.215191 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File '/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py', line 860 in _exec_template
[Tue Oct 11 14:37:56.215193 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   callable_(context, *args, **kwargs)
[Tue Oct 11 14:37:56.215195 2016] [:error] [pid 53387] [remote 10.111.80.101:40] File 'geoportailv3_templates_tooltip_default_html', line 27 in render_body
[Tue Oct 11 14:37:56.215199 2016] [:error] [pid 53387] [remote 10.111.80.101:40] MakoRenderingException:
[Tue Oct 11 14:37:56.215201 2016] [:error] [pid 53387] [remote 10.111.80.101:40]
[Tue Oct 11 14:37:56.215272 2016] [:error] [pid 53387] [remote 10.111.80.101:40] Traceback (most recent call last):
[Tue Oct 11 14:37:56.215276 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   File "/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
[Tue Oct 11 14:37:56.215283 2016] [:error] [pid 53387] [remote 10.111.80.101:40]     result = template.render_unicode(**system)
[Tue Oct 11 14:37:56.215296 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   File "/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode
[Tue Oct 11 14:37:56.215299 2016] [:error] [pid 53387] [remote 10.111.80.101:40]     as_unicode=True)
[Tue Oct 11 14:37:56.215301 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   File "/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 803, in _render
[Tue Oct 11 14:37:56.215303 2016] [:error] [pid 53387] [remote 10.111.80.101:40]     **_kwargs_for_callable(callable_, data))
[Tue Oct 11 14:37:56.215330 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   File "/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 835, in _render_context
[Tue Oct 11 14:37:56.215347 2016] [:error] [pid 53387] [remote 10.111.80.101:40]     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
[Tue Oct 11 14:37:56.215349 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   File "/var/www/vhosts/apiv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 860, in _exec_template
[Tue Oct 11 14:37:56.215351 2016] [:error] [pid 53387] [remote 10.111.80.101:40]     callable_(context, *args, **kwargs)
[Tue Oct 11 14:37:56.215353 2016] [:error] [pid 53387] [remote 10.111.80.101:40]   File "/var/www/vhosts/apiv3/geoportailv3/templates/tooltip/default.html", line 6, in render_body
[Tue Oct 11 14:37:56.215355 2016] [:error] [pid 53387] [remote 10.111.80.101:40]     <td>${feature['attributes'][attr]}</td>
[Tue Oct 11 14:37:56.215357 2016] [:error] [pid 53387] [remote 10.111.80.101:40] UnicodeEncodeError: 'ascii' codec can't encode character u'\\xe9' in position 12: ordinal not in range(128
```
