### ISSUE TITLE
api generation failed

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1639]
api generation failed on the followinf error. 
Should I update something ? 

```
 make -f renaud.mk build-api
mkdir -p geoportailv3/static/build/
node node_modules/openlayers/tasks/build.js jsapi/config.json geoportailv3/static/build/apiv3.js
info ol Parsing dependencies
info ol Compiling 355 sources
cat node_modules/proj4/dist/proj4.js node_modules/whatwg-fetch/fetch.js node_modules/d3/d3.min.js \
node_modules/js-autocomplete/auto-complete.min.js \
node_modules/promise-polyfill/promise.min.js \
geoportailv3/static/build/apiv3.js > concatenated.js
mv concatenated.js geoportailv3/static/build/apiv3.js
mkdir -p geoportailv3/static/build/
./node_modules/.bin/lessc --clean-css geoportailv3/static/less/geoportailv3.api.less geoportailv3/static/build/apiv3.css
node jsapi/jsdoc/get-ol3-doc-ref.js > .build/jsdocOl3.js.tmp

/home/mire/geoportailv3/node_modules/jsdom/lib/jsdom.js:3
() => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
 ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/mire/geoportailv3/jsapi/jsdoc/get-ol3-doc-ref.js:2:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
make: *** [.build/jsdocOl3.js] Error 8

```

**Comment by tonio** [comment]
Yes, the node version needs to be updated. I had to do [this](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/jsapi/.travis.yml#L9) for Travis.

**Comment by rmichaelis** [comment]
Ok thanks.
