### ISSUE TITLE
 --trusted-host is not a valid option in build

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#185]
Any idea ? 

 make -f renaud.mk build
.build/venv/bin/pip install --index-url http://pypi.camptocamp.net/pypi --find-links http://pypi.camptocamp.net/internal-pypi/index/c2cgeoportal --find-links http://pypi.camptocamp.net/internal-pypi/index/c2cgeoportal-win --trusted-host pypi.camptocamp.net -r CONST_versions.txt -e git+https://github.com/camptocamp/pyramid_closure#egg=pyramid_closure -e .

Usage:
  pip install [options] <requirement specifier> ...
  pip install [options] -r <requirements file> ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --trusted-host
make: *** [.build/eggs.timestamp] Error 2

**Comment by geoportallux** [comment]
make cleanall ...


Jeff Konnen
Chargé d’études – informaticien/Chef de projet

LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
Ministère des Finances
Administration du cadastre et de la topographie
Service informatique & Service géoportail

54, avenue Gaston Diderich . L-1420 Luxembourg
Tél. (+352) 44901-261<tel:(+352)%2044901-261> . Fax (+352) 44901-333<tel:(+352)%2044901-333>
E-mail: jeff.konnen@act.etat.lu
www.act.public.lu www.geoportail.lu


-----Original Message-----

**Comment by pgiraud** [comment]
Une nouvelle version de pip doit être installée.
Le `make cleanall` aide bien en effet.

On Tue, Jan 27, 2015 at 10:03 AM, geoportallux <notifications@github.com>
wrote:

> make cleanall ...
>
>
> Jeff Konnen
> Chargé d’études – informaticien/Chef de projet
>
> LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
> Ministère des Finances
> Administration du cadastre et de la topographie
> Service informatique & Service géoportail
>
> 54, avenue Gaston Diderich . L-1420 Luxembourg
> Tél. (+352) 44901-261<tel:(+352)%2044901-261> . Fax (+352) 44901-333<tel:(+352)%2044901-333>
>
> E-mail: jeff.konnen@act.etat.lu
> www.act.public.lu www.geoportail.lu
>
>
> -----Original Message-----
> From: rmichaelis [notifications@github.com]
> Received: 27 janv. 09:58
> To: Geoportail-Luxembourg/geoportailv3 [geoportailv3@noreply.github.com]
> Subject: [geoportailv3] --trusted-host is not a valid option in build
> (#185)
>
>
>
> Any idea ?
>
> make -f renaud.mk build
> .build/venv/bin/pip install --index-url http://pypi.camptocamp.net/pypi
> --find-links http://pypi.camptocamp.net/internal-pypi/index/c2cgeoportal
> --find-links
> http://pypi.camptocamp.net/internal-pypi/index/c2cgeoportal-win
> --trusted-host pypi.camptocamp.net -r CONST_versions.txt -e git+
> https://github.com/camptocamp/pyramid_closure#egg=pyramid_closure -e .
>
> Usage:
> pip install [options] ...
> pip install [options] -r ...
> pip install [options] [-e] ...
> pip install [options] [-e] ...
> pip install [options] ...
>
> no such option: --trusted-host
> make: *** [.build/eggs.timestamp] Error 2
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/Geoportail-Luxembourg/geoportailv3/issues/185>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Geoportail-Luxembourg/geoportailv3/issues/185#issuecomment-71612240>
> .
>



-- 
Pierre GIRAUD
Géomaticien, Analyste

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : 00 33 4 79 44 44 93
Mail : pierre.giraud@camptocamp.com
http://www.camptocamp.com

**Comment by rmichaelis** [comment]
Zut, j'ai à nouveau le problème de  "Bad md5 hash" quand je fais le cleanall.

**Comment by rmichaelis** [comment]
J'ai passé le problème du "Bad md5 hash" en installant la librairie Pillow manuellement.

Par contre nouvelle erreur : 
@sbrunner  J'essaye de faire un build sur le master et je recois l'erreur suivate de db2pot : 
database "lux" does not exist

Est-ce que j'ai besoin d'une configuration particulière ?


mkdir -p geoportailv3/locale/
.build/venv/bin/db2pot
Traceback (most recent call last):
  File ".build/venv/bin/db2pot", line 9, in <module>
    load_entry_point('c2cgeoportal==1.6.0.dev20150123', 'console_scripts', 'db2pot')()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/scripts/db2pot.py", line 40, in main
    env = bootstrap("development.ini")
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/paster.py", line 131, in bootstrap
    app = get_app(config_uri, options=options)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/paster.py", line 31, in get_app
    global_conf=options)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 203, in invoke
    app = context.app_context.create()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/mire/geoportailv3/geoportailv3/__init__.py", line 23, in main
    config.include('c2cgeoportal')
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 755, in include
    c(configurator)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/__init__.py", line 529, in includeme
    config.scan(ignore='c2cgeoportal.tests')
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 930, in scan
    ignore=ignore)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/venusian/__init__.py", line 205, in scan
    __import__(modname)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/forms.py", line 50, in <module>
    from c2cgeoportal import models
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/models.py", line 74, in <module>
    postgis_version = DBSession.execute(func.postgis_version()).scalar()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 991, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 858, in _connection_for_bind
    return self.transaction._connection_for_bind(engine)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 322, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1798, in contextual_connect
    self.pool.connect(),
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 338, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 644, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 440, in checkout
    rec = pool._do_get()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 963, in _do_get
    return self._create_connection()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 285, in _create_connection
    return _ConnectionRecord(self)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 411, in __init__
    self.connection = self.__connect()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 538, in __connect
    connection = self.__pool._creator()
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 96, in connect
    connection_invalidated=invalidated
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 90, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (OperationalError) FATAL:  database "lux" does not exist

**Comment by rmichaelis** [comment]
J'ai refait un clean et c'est passé. 
C'est en ordre.
