### ISSUE TITLE
Embeded iframe does not load when third-party cookies are disabled

### ISSUE THREAD

**Issue by PitWenkin** [Geoportail-Luxembourg/geoportailv3#2660]
When  disabling third-party cookies in browser,  localstorage, sessionstorage, and ServiceWorkers might be blocked for iframes.

Error in Chrome console:
```
Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://map.geoportail.lu/') with script ('https://map.geoportail.lu/sw.js'): The user denied permission to use Service Worker.
Promise.then (async)
(anonymous) @ main?version=3&zoom=18&X=677460&Y=6356836&lang=fr&rotation=0&layers=546&opacities=1&bgLayer=basemap_2015_global&crosshair=true&embedded=true:39
```

Should be this line:

 https://github.com/Geoportail-Luxembourg/geoportailv3/blob/48eddcaf559dab171d6849677eb73a2fd1e2f150/geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs#L39

Adding a `catch` might fix it.

**Comment by PitWenkin** [comment]
Error in Chrome console:
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.<anonymous> (https://map.geoportail.lu/static-ngeo/UNUSED_CACHE_VERSION/build/main.cdee93.js:214:29557)
    at r (https://map.geoportail.lu/static-ngeo/UNUSED_CACHE_VERSION/build/main.cdee93.js:1:107)
    at Object.<anonymous> (https://map.geoportail.lu/static-ngeo/UNUSED_CACHE_VERSION/build/main.cdee93.js:193:64323)
    at Object.<anonymous> (https://map.geoportail.lu/static-ngeo/UNUSED_CACHE_VERSION/build/main.cdee93.js:193:87977)
    at r (https://map.geoportail.lu/static-ngeo/UNUSED_CACHE_VERSION/build/main.cdee93.js:1:107)
    at https://map.geoportail.lu/static-ngeo/UNUSED_CACHE_VERSION/build/main.cdee93.js:1:610
    at https://map.geoportail.lu/static-ngeo/UNUSED_CACHE_VERSION/build/main.cdee93.js:1:622
(anonymous) @ MvtStylingService.js:11
r @ bootstrap:19
(anonymous) @ MainController.js:1
(anonymous) @ MainController.js:1688
r @ bootstrap:19
(anonymous) @ bootstrap:68
(anonymous) @ bootstrap:68
```

Should be this line:


https://github.com/Geoportail-Luxembourg/geoportailv3/blob/639bcbaac62d731c3695b7e004a9ec0e0bb66209/geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js#L11

Adding  the ` hasLocalStorage()`-function migth fix it.

**Comment by rmichaelis** [comment]
thank for reporting this issue.
It should be fixed now.

**Comment by PitWenkin** [comment]
There are still some uncaught promise errors, but the map is  loading now.

Thanks
