### ISSUE TITLE
sqlalchemy.exc.ArgumentError at application init time

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#517]
Since https://github.com/Geoportail-Luxembourg/geoportailv3/pull/452 was merged I get an error at application init time:

```
-------------------- Restarting --------------------
Traceback (most recent call last):
  File ".build/venv/bin/pserve", line 9, in <module>
    load_entry_point('pyramid==1.6.dev0', 'console_scripts', 'pserve')()
  File "/home/elemoine/src/geoportailv3/.build/venv/src/pyramid/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/home/elemoine/src/geoportailv3/.build/venv/src/pyramid/pyramid/scripts/pserve.py", line 328, in run
    global_conf=vars)
  File "/home/elemoine/src/geoportailv3/.build/venv/src/pyramid/pyramid/scripts/pserve.py", line 363, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 203, in invoke
    app = context.app_context.create()
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/elemoine/src/geoportailv3/geoportailv3/__init__.py", line 68, in main
    sqlalchemy.create_engine(engines[engine]), name=engine)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 362, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 49, in create
    u = url.make_url(name_or_url)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 176, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 225, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name)
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'Allow from 127.0.0.1 ::1'
```

This is related to `sqlalchemy_engines` [variable](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/7f6aabbcbeffe1f8a7371003f0fbad85d37522ed/geoportailv3.mk#L19) that was added by #452.

Does anyone know what's going on?

**Comment by elemoine** [comment]
This is what I see in my `.build/config.yaml` file:

```
sqlalchemy_engines: *id014
```
and `id014` corresponds to something unrelated:

```
layers: &id014
  admin_interface: *id001
  apache_entry_point: /elemoine/
  authtkt: {cookie_name: auth_tkt_elemoine, secret: a791e66e7b174f698793044a7523fadc}
  ...
```

This problem is blocking me…

**Comment by jaykayone** [comment]
maybe you should apply the alembic script?

**Comment by elemoine** [comment]
> maybe you should apply the alembic script?

Sounds unrelated to migrating the database to me, but I may be wrong here…

**Comment by rmichaelis** [comment]
adding this entry in your vars_elemoine.yaml could be a workaround.

    sqlalchemy_engines:
        ecadastre: 'postgresql:/user:password@db.geoportal.lu/ecadastre'

**Comment by elemoine** [comment]
Yep, I'll try that. But I don't understand why I get garbage for `sqlalchemy_engines` (`'Allow from 127.0.0.1 ::1'` is the garbage I'm referring to) when `sqlalchemy_engines` is not defined in my configuration. @sbrunner?

**Comment by elemoine** [comment]
The workaround works. @rmichaelis, where is `sqlalchemy_engines` defined in your case? In a config file not committed into the project?

**Comment by rmichaelis** [comment]
sqlalchemy_engines is configured in my local yaml file.

But because of this line : 
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3.mk#L19

I have to add a fake entry in the file vars_geoportailv3.yaml

**Comment by elemoine** [comment]
Yes, there shouldn't be anything in geoportailv3.mk that requires a local change.
