### ISSUE TITLE
error after upgrade

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#561]
after upgrading to the newest c2cgeoportal, I encounter the following error:

```
 mod_wsgi (pid=11342): Target WSGI script '/var/www/vhosts/geoportailv3/apache/geoportailv3.wsgi' cannot be loaded as Python module.
 mod_wsgi (pid=11342): Exception occurred processing WSGI script '/var/www/vhosts/geoportailv3/apache/geoportailv3.wsgi'.
 Traceback (most recent call last):
   File "/var/www/vhosts/geoportailv3/apache/geoportailv3.wsgi", line 12, in <module>
     application = get_app('/var/www/vhosts/geoportailv3/production.ini', 'main')
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/paster.py", line 31, in get_app
     global_conf=options)
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
     return loadobj(APP, uri, name=name, **kw)
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
     return context.create()
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
     return self.object_type.invoke(self)
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 203, in invoke
     app = context.app_context.create()
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
     return self.object_type.invoke(self)
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
     return fix_call(context.object, context.global_conf, **context.local_conf)
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
     val = callable(*args, **kw)
   File "/var/www/vhosts/geoportailv3/geoportailv3/__init__.py", line 89, in main
     return config.make_wsgi_app()
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 973, in make_wsgi_app
     self.commit()
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 642, in commit
     self.action_state.execute_actions(introspector=self.introspector)
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 1150, in execute_actions
     action = next(pending_actions, None)
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 1108, in resume
     for a, b in zip_longest(actions, executed_actions):
   File "/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/config/__init__.py", line 1286, in resolveConflicts
     raise ConfigurationConflictError(conflicts)
 ConfigurationConflictError: Conflicting configuration actions
   For: ('route', 'printproxy_report_create')
     Line 549 of file /var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/__init__.py:
         config.add_route("printproxy_report_create", "/printproxy/report.{format}")
     Line 553 of file /var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/__init__.py:
         request_method="POST",
   For: ('route', 'printproxy_status')
     Line 550 of file /var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/__init__.py:
         config.add_route("printproxy_status", "/printproxy/status/{ref}.json")
     Line 557 of file /var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/__init__.py:
         request_method="GET",
```

**Comment by petzlux** [comment]
me too after rebase ...

**Comment by sbrunner** [comment]
Personally I have this error:
```
./node_modules/openlayers/node_modules/.bin/closure-util build build.json .build/build.js
info closure-util Reading build config
info closure-util Getting Closure dependencies
ERR! closure-util Unsatisfied dependency "ol.FeatureOverlay" in script: /home/sbrunner/geoportailv3/node_modules/ngeo/src/ol-ext/interaction/measure.js
make: *** [.build/build.js] Error 1
```
:-(

**Comment by rmichaelis** [comment]
@sbrunner a clean should solve this problem.

**Comment by elemoine** [comment]
@sbrunner, you have this problem because you don't have the correct version of OpenLayers 3 installed in `node_modules`. A `make update-node-modules` should fix the problem.

**Comment by sbrunner** [comment]
I do a ``cleanall`` :-(
