### ISSUE TITLE
print does not work anymore ..

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#678]
```org.mapfish.print.wrapper.ObjectMissingException: attribute [spec.attributes.map.layers.[0]] missing
	at org.mapfish.print.wrapper.json.PJsonArray.getJSONObject(PJsonArray.java:73) ~[PJsonArray.class:na]
	at org.mapfish.print.wrapper.json.PJsonArray.getObject(PJsonArray.java:62) ~[PJsonArray.class:na]
	at org.mapfish.print.attribute.map.GenericMapAttribute$GenericMapAttributeValues.parseLayers(GenericMapAttribute.java:277) ~[GenericMapAttribute$GenericMapAttributeValues.class:na]
	at org.mapfish.print.attribute.map.GenericMapAttribute$GenericMapAttributeValues.postConstruct(GenericMapAttribute.java:269) ~[GenericMapAttribute$GenericMapAttributeValues.class:na]
	at org.mapfish.print.attribute.map.MapAttribute$MapAttributeValues.postConstruct(MapAttribute.java:141) ~[MapAttribute$MapAttributeValues.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at org.mapfish.print.parser.MapfishParser.parse(MapfishParser.java:139) ~[MapfishParser.class:na]
	at org.mapfish.print.output.Values.populateFromAttributes(Values.java:196) ~[Values.class:na]
	at org.mapfish.print.output.Values.<init>(Values.java:129) ~[Values.class:na]
	at org.mapfish.print.output.AbstractJasperReportOutputFormat.getJasperPrint(AbstractJasperReportOutputFormat.java:151) ~[AbstractJasperReportOutputFormat.class:na]
	at org.mapfish.print.output.AbstractJasperReportOutputFormat.print(AbstractJasperReportOutputFormat.java:109) ~[AbstractJasperReportOutputFormat.class:na]
	at org.mapfish.print.MapPrinter.print(MapPrinter.java:138) ~[MapPrinter.class:na]
	at org.mapfish.print.servlet.job.PrintJob$1.run(PrintJob.java:134) ~[PrintJob$1.class:na]
	at org.mapfish.print.servlet.job.FilePrintJob.withOpenOutputStream(FilePrintJob.java:50) ~[FilePrintJob.class:na]
	at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:131) [PrintJob.class:na]
	at org.mapfish.print.servlet.job.PrintJob.call(PrintJob.java:56) [PrintJob.class:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
16:55:22.632 [PrintJobManager-1] DEBUG o.mapfish.print.servlet.job.PrintJob - Print Job bdcee5cf-bf77-4748-b7d0-8844ade5e1c2@c8ecd8c6-fb69-41c0-b186-a54d79f4a8a9 completed in 7ms
16:55:23.724 [http-bio-0.0.0.0-8083-exec-7] ERROR o.m.print.servlet.BaseMapServlet - Error while processing request: org.mapfish.print.wrapper.ObjectMissingException: attribute [spec.attributes.map.layers.[0]] missing```
Is this due to an updated version of c2cgeoportal?

**Comment by jaykayone** [comment]
this is a cache problem.

deleting it

**Comment by elemoine** [comment]
I got really really scared!

**Comment by jaykayone** [comment]
so did I :)
